# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c1b0abc62ea65878cd1068189eca1446edd42293bab1fcbcc4d0c2c64718f57da1bdfca8c1b1c06801fc42ec2a6784359a2a097236bdff91b37596baf0f97d23

test:
  secret_key_base: 7f2c04633fb53902cc89ba8bc98650cf3dde6c8c3853ca659f85a5153016a15ef158a01d90a7bdc732699ce0e57b0759cb2aa53b975aa0c33ecd418e37a14e5d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
